import { Document, Types } from 'mongoose';

/**
 * Work Order Types - Maintenance/Workshop Module
 * 
 * Work Orders are auto-generated when a CustomerOrder is created (cascaded from Sales Order).
 * They blend inherited data from CustomerOrder with new maintenance-specific fields.
 */

// ─────────────────────────────────────────────────────────────────────────────
// Enums
// ─────────────────────────────────────────────────────────────────────────────

export enum Punctuality {
    SameTime = 'Same time',
    Late     = 'Late',
    Empty    = '',
}

export enum TaskCompleted {
    Yes   = 'Yes',
    No    = 'No',
    Empty = '',
}

export enum SparePartsAvailability {
    Available    = 'Available',
    NotAvailable = 'Not Available',
    Requested    = 'Requested',
    Empty        = '',
}

// ─────────────────────────────────────────────────────────────────────────────
// Legacy Enums (kept for backward compatibility with existing data)
// ─────────────────────────────────────────────────────────────────────────────

export enum OrderType {
    Maintenance      = 'Maintenance',
    GeneralSupplies  = 'General supplies',
    SupplyAndInstall = 'Supply and installation',
}

export enum LateDurationType {
    Hours = 'Hours',
    Days  = 'Days',
}

export enum DevicePickupType {
    Workshop = 'Workshop',
    OnSite   = 'On-Site',
    NotSet   = '',
}

// ─────────────────────────────────────────────────────────────────────────────
// Interfaces
// ─────────────────────────────────────────────────────────────────────────────

export interface IWorkOrder {
    // Required: Reference to CustomerOrder (inherits customer, sales, and ops data)
    customerOrderId: Types.ObjectId;
    
    // Workshop / Maintenance Specific Fields
    taskDate?:              Date;       // Op role task date
    maintenanceEngineer:    string;     // Name of the maintenance engineer
    startMaintenanceDate?:  Date;
    endMaintenanceDate?:    Date;
    punctuality:            Punctuality;
    reasonForDelay:         string;
    taskCompleted:          TaskCompleted;
    reasonForIncompletion:  string;
    rating:                 string;
    sparePartsId:           string;
    sparePartsAvailability: SparePartsAvailability;
    notes:                  string;
    
    // Tracking
    updatedBy?: Types.ObjectId;   // → User who last modified
    
    // Timestamps (auto-generated by Mongoose)
    createdAt: Date;
    updatedAt: Date;
}

export interface IWorkOrderDocument extends IWorkOrder, Document {
    _id: Types.ObjectId;
}
