import { Document, Types } from 'mongoose';

/**
 * Work Order Types - Maintenance/Workshop Module
 * 
 * Work Orders are auto-generated when a CustomerOrder is created (cascaded from Sales Order).
 * They blend inherited data from CustomerOrder with new maintenance-specific fields.
 */

// ─────────────────────────────────────────────────────────────────────────────
// Enums
// ─────────────────────────────────────────────────────────────────────────────

export enum Punctuality {
    SameTime = 'Same time',
    Late     = 'Late',
    Empty    = '',
}

export enum TaskCompleted {
    Yes   = 'Yes',
    No    = 'No',
    Empty = '',
}

export enum SparePartsAvailability {
    Available    = 'Available',
    NotAvailable = 'Not Available',
    Requested    = 'Requested',
    Empty        = '',
}

// ─────────────────────────────────────────────────────────────────────────────
// Legacy Enums (kept for backward compatibility with existing data)
// ─────────────────────────────────────────────────────────────────────────────

export enum OrderType {
    Maintenance      = 'Maintenance',
    GeneralSupplies  = 'General supplies',
    SupplyAndInstall = 'Supply and installation',
}

export enum LateDurationType {
    Hours = 'Hours',
    Days  = 'Days',
}

export enum DevicePickupType {
    Workshop = 'Workshop',
    OnSite   = 'On-Site',
    NotSet   = '',
}

// ─────────────────────────────────────────────────────────────────────────────
// Interfaces
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Part used in a work order
 */
export interface IWorkOrderPart {
    inventoryItemId: Types.ObjectId;  // Reference to InventoryFinance
    quantity: number;                 // Quantity used
    unitCost: number;                 // Unit cost
}

/**
 * Work order cost summary
 */
export interface IWorkOrderCost {
    partsTotal: number;              // Sum of all parts costs
    laborCost: number;               // Labor cost (if applicable)
    otherCosts: number;              // Other costs
    grandTotal: number;               // Total cost
}

export interface IWorkOrder {
    // Required: Reference to CustomerOrder (inherits customer, sales, and ops data)
    customerOrderId: Types.ObjectId;
    
    // Workshop / Maintenance Specific Fields
    taskDate?:              Date;       // Op role task date
    maintenanceEngineer:    string;     // Name of the maintenance engineer
    startMaintenanceDate?:  Date;
    endMaintenanceDate?:    Date;
    punctuality:            Punctuality;
    reasonForDelay:         string;
    taskCompleted:          TaskCompleted;
    reasonForIncompletion: string;
    rating:                 string;
    sparePartsAvailability: SparePartsAvailability;
    notes:                  string;
    
    // Parts usage tracking (integration with Inventory)
    partsUsed: IWorkOrderPart[];
    cost: IWorkOrderCost;
    actualCost?: number;  // Calculated actual cost of parts used after deduction
    
    // Tracking
    updatedBy?: Types.ObjectId;   // → User who last modified
    
    // Timestamps (auto-generated by Mongoose)
    createdAt: Date;
    updatedAt: Date;
}

export interface IWorkOrderDocument extends IWorkOrder, Document {
    _id: Types.ObjectId;
}
