import { Document, Types } from 'mongoose';

export enum InvoiceStatus {
    Draft = 'Draft',
    Sent = 'Sent',
    Paid = 'Paid',
    Overdue = 'Overdue',
    Cancelled = 'Cancelled',
}

export interface IInvoiceItem {
    description: string;
    quantity: number;
    unitPrice: number;
    salesOrderItemId?: string;
}

export interface IInvoice {
    invoiceNumber: string;
    client?: Types.ObjectId;
    // Integration: Link to Sales Order and Customer
    salesOrderId?: Types.ObjectId;
    customerOrderId?: Types.ObjectId;
    customerId?: Types.ObjectId;
    items: IInvoiceItem[];
    subtotal: number;
    tax: number;
    total: number;
    status: InvoiceStatus;
    issueDate: Date;
    dueDate?: Date;
    paidAt?: Date;
    // Payment tracking
    paymentMethod?: string;
    paymentReference?: string;
    // Auto-generation flag
    autoGenerated?: boolean;
    notes?: string;
    createdAt: Date;
    updatedAt: Date;
}

export interface IInvoiceDocument extends IInvoice, Document {
    _id: Types.ObjectId;
}

