import { Schema, model, Document, Types } from 'mongoose';

export interface ISalary extends Document {
  employeeId: Types.ObjectId;  // ObjectId reference to Employee (migrated from String)
  employeeName: string;
  department: string;
  basicSalary: number;
  allowances: number;
  overtime: number;
  bonuses: number;
  percentage: string;
  tax: number;
  insurance: number;
  absenceDeduction: number;
  otherDeductions: number;
  month: number;  // Salary month (1-12)
  year: number;   // Salary year
  autoGenerated: boolean;  // Flag indicating if salary was auto-generated
  attendanceDetails?: {
    totalDays: number;
    presentDays: number;
    absentDays: number;
    lateDays: number;
    halfDays: number;
  };
  notes?: string;
}

const SalarySchema = new Schema<ISalary>({
  employeeId: { type: Schema.Types.ObjectId, ref: 'Employee', required: true },
  employeeName: { type: String, required: true },
  department: { type: String, required: true },
  basicSalary: { type: Number, required: true },
  allowances: { type: Number, default: 0 },
  overtime: { type: Number, default: 0 },
  bonuses: { type: Number, default: 0 },
  percentage: { type: String, default: '0%' },
  tax: { type: Number, default: 0 },
  insurance: { type: Number, default: 0 },
  absenceDeduction: { type: Number, default: 0 },
  otherDeductions: { type: Number, default: 0 },
  month: { type: Number, required: true, min: 1, max: 12 },
  year: { type: Number, required: true, min: 2020 },
  autoGenerated: { type: Boolean, default: false },
  attendanceDetails: {
    totalDays: { type: Number, default: 0 },
    presentDays: { type: Number, default: 0 },
    absentDays: { type: Number, default: 0 },
    lateDays: { type: Number, default: 0 },
    halfDays: { type: Number, default: 0 },
  },
  notes: { type: String },
}, {
  timestamps: true,
});

// Compound unique index to prevent duplicate salary records per employee per month
SalarySchema.index({ employeeId: 1, month: 1, year: 1 }, { unique: true });

export const Salary = model<ISalary>('Salary', SalarySchema);
